name: Publish Docs on Release
on:
  release:
    types: [created]
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mutablelogic'

    - name: Generate Documentatin
      run: |
        npm install
        npm run docs

    - name: Deploy Documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/doc
