name: Package Publish on Release
on:
  release:
    types: [created]
jobs:
  var:
    name: Set variables
    runs-on: ubuntu-latest
    steps:
    - name: Set variables
      id: var
      run: |
        TAG="$(git describe --tags)" && echo "tag=${TAG#v}" >> $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.var.outputs.tag }}
  build:
    name: Build
    needs: var    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mutablelogic'
    - name: Publish
      run: |
        npm ci
        npm version ${{ needs.var.outputs.tag }} --no-git-tag-version --allow-same-version
        npm run build
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
